name: test

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build_infrastructure:
    name: "Initialize and Plan Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out repo code"
        uses: actions/checkout@v2
      - name: "Initialize Modules"
        run: |
          cd infrastructure/aks
          terraform init
      - name: "Plan Infrastructure"
        run: |
          cd infrastructure/aks
          terraform plan
  build_test_app:
    name: "Build and Test App"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: "Checking out repo code"
        uses: actions/checkout@v2

      - name: "Validate build"
        run: |
          cd app
          npm install
          npm run build

      - name: "Run tests"
        run: |
          cd app
          npm run test

      - name: "Run test coverage"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $coverage_result = npm run coverage
          $start = $false;
          $middle = $false; 
          $end = $false; 
          $count = 0; 
          foreach ($j in $coverage_result) 
          { 
            if ($j.tostring().startswith("--------------")) 
            { 
                  if (!$start) 
                  { 
                      $start = $true;
                      $start_index = $count 
                  } 
                  elseif (!$middle) 
                  {
                      $middle = $true; 
                      $middle_index = $count 
                  } 
                  elseif (!$end) 
                  { 
                      $end = $true; 
                      $end_index = $count 
                  } 
            }
            $count++
          }
          $tbl_md = $coverage_result[($start_index+1)..($end_index-1)] -join "\n"
          $summary = $coverage_result[($end_index + 1)..$count] -join "\n"
          $comment = $tbl_md + "\n" + $summary
          $url = "https://api.github.com/repos/${env:GITHUB_REPOSITORY}/issues/${env:PR_NUMBER}/comments"
          $headers = @{
            "Authorization" = "token ${env:GITHUB_TOKEN}"
          }
          Invoke-RestMethod -Method POST -Uri $url -Headers $headers -Body "{ `"body`": `"${comment}`" }"
